### ISSUE TITLE
Avatar images

### ISSUE THREAD

**Issue by jiserra** [jimrutherford/Random-User#3]
Does this script could help with retrieving images?

https://github.com/timuric/Content-generator-for-sketch-app/blob/master/loadImage.js

Thanks for the plugin, it's ace!

**Comment by jimrutherford** [comment]
I'm working on this feature today actually!  Hopefully I'll push it out before the end of the day.

Thanks!

**Comment by jiserra** [comment]
Great to hear! :+1:
